export const SELECT_CITY = 'SELECT_CITY'

export const REQUEST_CITIES = 'REQUEST_CITIES'
export const RECEIVE_CITIES = 'RECEIVE_CITIES'


export const LOAD_FAVORITES_LIST = 'LOAD_FAVORITES_LIST'
export const CHANGE_FAVORITES = 'CHANGE_FAVORITES'

export const CHANGE_INPUT_TEXT = 'CHANGE_INPUT_TEXT'